language: perl
perl:
  - blead       # builds perl from git
  - dev         # latest point release
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
  - '5.8'
install:
  - cpanm --quiet --notest YAML::Tiny File::Remove Module::Build Module::ScanDeps Parse::CPAN::Meta
  - perl Makefile.PL
  - cpanm --quiet --installdeps --notest .
